"""Add custom_wine_region and custom_wine_country columns

Revision ID: b9c9353aed81
Revises: f0e8cfe4df2c
Create Date: 2026-01-26 07:04:05.881664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9c9353aed81'
down_revision: Union[str, Sequence[str], None] = 'f0e8cfe4df2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cellar_bottles', sa.Column('custom_wine_region', sa.String(length=100), nullable=True))
    op.add_column('cellar_bottles', sa.Column('custom_wine_country', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cellar_bottles', 'custom_wine_country')
    op.drop_column('cellar_bottles', 'custom_wine_region')
    # ### end Alembic commands ###
