"""Add custom_wine_varietal column

Revision ID: f0e8cfe4df2c
Revises: f04bb5b122be
Create Date: 2026-01-25 17:44:07.193669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e8cfe4df2c'
down_revision: Union[str, Sequence[str], None] = 'f04bb5b122be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cellar_bottles', sa.Column('custom_wine_varietal', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cellar_bottles', 'custom_wine_varietal')
    # ### end Alembic commands ###
